version: 7
profiles:
  - type: ssh
    name: android156
    icon: fas fa-desktop
    options:
      host: android156
      user: yclv
      algorithms:
        hmac:
          - hmac-sha1
          - hmac-sha1-etm@openssh.com
          - hmac-sha2-256
          - hmac-sha2-256-etm@openssh.com
          - hmac-sha2-512
          - hmac-sha2-512-etm@openssh.com
        kex:
          - curve25519-sha256
          - curve25519-sha256@libssh.org
          - diffie-hellman-group14-sha256
          - diffie-hellman-group16-sha512
          - ext-info-c
          - ext-info-s
          - kex-strict-c-v00@openssh.com
          - kex-strict-s-v00@openssh.com
        cipher:
          - aes128-ctr
          - aes192-ctr
          - aes256-ctr
          - aes256-gcm@openssh.com
          - chacha20-poly1305@openssh.com
        serverHostKey:
          - ecdsa-sha2-nistp256
          - ecdsa-sha2-nistp521
          - rsa-sha2-256
          - rsa-sha2-512
          - ssh-ed25519
          - ssh-rsa
      input: {}
      privateKeys: []
      forwardedPorts: []
      scripts: []
    weight: -1
    id: ssh:custom:android156:45465840-04c1-4fe8-9920-784f4a5e8e1e
  - type: ssh
    name: fedora42
    icon: fas fa-desktop
    options:
      host: fedora42
      user: lysander
      algorithms:
        hmac:
          - hmac-sha1
          - hmac-sha1-etm@openssh.com
          - hmac-sha2-256
          - hmac-sha2-256-etm@openssh.com
          - hmac-sha2-512
          - hmac-sha2-512-etm@openssh.com
        kex:
          - curve25519-sha256
          - curve25519-sha256@libssh.org
          - diffie-hellman-group14-sha256
          - diffie-hellman-group16-sha512
          - ext-info-c
          - ext-info-s
          - kex-strict-c-v00@openssh.com
          - kex-strict-s-v00@openssh.com
        cipher:
          - aes128-ctr
          - aes192-ctr
          - aes256-ctr
          - aes256-gcm@openssh.com
          - chacha20-poly1305@openssh.com
        serverHostKey:
          - ecdsa-sha2-nistp256
          - ecdsa-sha2-nistp521
          - rsa-sha2-256
          - rsa-sha2-512
          - ssh-ed25519
          - ssh-rsa
      input: {}
      privateKeys: []
      forwardedPorts: []
      scripts: []
    weight: -1
    id: ssh:custom:fedora42:aa9276c2-fe7a-4716-a67d-8c4462be89e6
  - type: ssh
    name: liutr_acloud
    icon: fas fa-desktop
    options:
      host: 120.77.32.149
      algorithms:
        hmac:
          - hmac-sha1
          - hmac-sha1-etm@openssh.com
          - hmac-sha2-256
          - hmac-sha2-256-etm@openssh.com
          - hmac-sha2-512
          - hmac-sha2-512-etm@openssh.com
        kex:
          - curve25519-sha256
          - curve25519-sha256@libssh.org
          - diffie-hellman-group14-sha256
          - diffie-hellman-group16-sha512
          - ext-info-c
          - ext-info-s
          - kex-strict-c-v00@openssh.com
          - kex-strict-s-v00@openssh.com
        cipher:
          - aes128-ctr
          - aes192-ctr
          - aes256-ctr
          - aes256-gcm@openssh.com
          - chacha20-poly1305@openssh.com
        serverHostKey:
          - ecdsa-sha2-nistp256
          - ecdsa-sha2-nistp521
          - rsa-sha2-256
          - rsa-sha2-512
          - ssh-ed25519
          - ssh-rsa
      input: {}
      privateKeys: []
      forwardedPorts: []
      scripts: []
    weight: -1
    id: ssh:custom:liutr_acloud:84aa4e64-2755-4d58-a29d-556e00f9398a
  - type: ssh
    icon: fas fa-desktop
    options:
      host: mywin10
      user: lysander
      algorithms:
        hmac:
          - hmac-sha1
          - hmac-sha1-etm@openssh.com
          - hmac-sha2-256
          - hmac-sha2-256-etm@openssh.com
          - hmac-sha2-512
          - hmac-sha2-512-etm@openssh.com
        kex:
          - curve25519-sha256
          - curve25519-sha256@libssh.org
          - diffie-hellman-group14-sha256
          - diffie-hellman-group16-sha512
          - ext-info-c
          - ext-info-s
          - kex-strict-c-v00@openssh.com
          - kex-strict-s-v00@openssh.com
        cipher:
          - aes128-ctr
          - aes192-ctr
          - aes256-ctr
          - aes256-gcm@openssh.com
          - chacha20-poly1305@openssh.com
        serverHostKey:
          - ecdsa-sha2-nistp256
          - ecdsa-sha2-nistp521
          - rsa-sha2-256
          - rsa-sha2-512
          - ssh-ed25519
          - ssh-rsa
      input: {}
      privateKeys: []
      forwardedPorts: []
      scripts: []
    weight: -1
    name: myWin10
    id: ssh:custom:myWin10:c081c90d-7e71-4711-84a9-6cccc9468a37
  - type: ssh
    icon: fas fa-desktop
    options:
      host: freebsd14
      user: lysander
      algorithms:
        hmac:
          - hmac-sha1
          - hmac-sha1-etm@openssh.com
          - hmac-sha2-256
          - hmac-sha2-256-etm@openssh.com
          - hmac-sha2-512
          - hmac-sha2-512-etm@openssh.com
        kex:
          - curve25519-sha256
          - curve25519-sha256@libssh.org
          - diffie-hellman-group14-sha256
          - diffie-hellman-group16-sha512
          - ext-info-c
          - ext-info-s
          - kex-strict-c-v00@openssh.com
          - kex-strict-s-v00@openssh.com
        cipher:
          - aes128-ctr
          - aes192-ctr
          - aes256-ctr
          - aes256-gcm@openssh.com
          - chacha20-poly1305@openssh.com
        serverHostKey:
          - ecdsa-sha2-nistp256
          - ecdsa-sha2-nistp521
          - rsa-sha2-256
          - rsa-sha2-512
          - ssh-ed25519
          - ssh-rsa
      input: {}
      privateKeys: []
      forwardedPorts: []
      scripts: []
    weight: -1
    name: freebsd14
    id: ssh:custom:freebsd14:5bc9647b-e0c1-4ef7-83d8-6d0072964d5b
groups: []
configSync:
  parts: {}
hotkeys:
  toggle-window: []
  copy-current-path: []
  ctrl-c:
    - Ctrl-C
  copy:
    - Ctrl-Shift-C
  paste:
    - Ctrl-Shift-V
    - Shift-Insert
  select-all: []
  clear: []
  zoom-in:
    - Ctrl-=
    - Ctrl-Shift-=
  zoom-out:
    - Ctrl--
    - Ctrl-Shift--
  reset-zoom:
    - Ctrl-0
  home:
    - Home
  end:
    - End
  previous-word:
    - Ctrl-Left
  next-word:
    - Ctrl-Right
  delete-previous-word:
    - Ctrl-Backspace
  delete-line:
    - Ctrl-Shift-Backspace
  delete-next-word:
    - Ctrl-Delete
  search:
    - Ctrl-Shift-F
  pane-focus-all:
    - Ctrl-Shift-I
  focus-all-tabs:
    - Ctrl-Alt-Shift-I
  scroll-to-top:
    - Ctrl-PageUp
  scroll-page-up:
    - Alt-PageUp
  scroll-up:
    - Ctrl-Shift-Up
  scroll-down:
    - Ctrl-Shift-Down
  scroll-page-down:
    - Alt-PageDown
  scroll-to-bottom:
    - Ctrl-PageDown
  restart-telnet-session: []
  restart-ssh-session: []
  launch-winscp: []
  settings-tab: {}
  settings:
    - Ctrl-,
  serial:
    - Alt-K
  restart-serial-session: []
  new-tab:
    - Ctrl-Shift-T
  new-window:
    - Ctrl-Shift-N
  profile: {}
  profile-selectors: {}
  group-selectors: {}
  toggle-fullscreen:
    - F11
  close-tab:
    - Ctrl-Shift-W
  reopen-tab:
    - Ctrl-Shift-Z
  rename-tab: []
  next-tab:
    - Ctrl-Shift-Right
    - Ctrl-Tab
  previous-tab:
    - Ctrl-Shift-Left
    - Ctrl-Shift-Tab
  move-tab-left:
    - Ctrl-Shift-PageUp
  move-tab-right:
    - Ctrl-Shift-PageDown
  rearrange-panes:
    - Ctrl-Shift
  duplicate-tab:
    - Ctrl-P
  restart-tab: []
  reconnect-tab:
    - Ctrl-Shift-R
  disconnect-tab: []
  explode-tab:
    - Ctrl-Shift-.
  combine-tabs:
    - Ctrl-Shift-,
  tab-1:
    - Alt-1
  tab-2:
    - Alt-2
  tab-3:
    - Alt-3
  tab-4:
    - Alt-4
  tab-5:
    - Alt-5
  tab-6:
    - Alt-6
  tab-7:
    - Alt-7
  tab-8:
    - Alt-8
  tab-9:
    - Alt-9
  tab-10:
    - Alt-0
  tab-11:
    - Alt--
  tab-12: []
  tab-13: []
  tab-14: []
  tab-15:
    - Alt-=
  tab-16: []
  tab-17: []
  tab-18: []
  tab-19: []
  tab-20: []
  split-right:
    - Ctrl-Shift-L
  split-bottom:
    - Ctrl-Shift-J
  split-left:
    - Ctrl-Shift-H
  pane-nav-right:
    - Ctrl-Alt-Right
  pane-nav-down:
    - Ctrl-Alt-Down
  pane-nav-up:
    - Ctrl-Alt-Up
  pane-nav-left:
    - Ctrl-Alt-Left
  pane-nav-previous:
    - Ctrl-Alt-[
  pane-nav-next:
    - Ctrl-Alt-]
  pane-nav-1: []
  pane-nav-2: []
  pane-nav-3: []
  pane-nav-4: []
  pane-nav-5: []
  pane-nav-6: []
  pane-nav-7: []
  pane-nav-8: []
  pane-nav-9: []
  pane-maximize:
    - Ctrl-Alt-Enter
  pane-increase-vertical: []
  pane-decrease-vertical: []
  pane-increase-horizontal: []
  pane-decrease-horizontal: []
  close-pane: []
  switch-profile:
    - Ctrl-Alt-T
  profile-selector:
    - Ctrl-Shift-E
  command-selector:
    - Ctrl-Shift-P
  split-top:
    - Ctrl-Shift-K
  toggle-last-tab: []
terminal:
  searchOptions: {}
  colorScheme:
    name: DimmedMonokai
    foreground: '#b9bcba'
    background: rgb(34, 37, 40)
    cursor: '#f83e19'
    colors:
      - '#3a3d43'
      - '#be3f48'
      - '#879a3b'
      - '#c5a635'
      - '#4f76a1'
      - '#855c8d'
      - '#578fa4'
      - '#b9bcba'
      - '#888987'
      - '#fb001f'
      - '#0f722f'
      - '#c47033'
      - '#186de3'
      - '#fb0067'
      - '#2e706d'
      - '#fdffb9'
  lightColorScheme:
    name: DimmedMonokai
    foreground: '#b9bcba'
    background: rgb(34, 37, 40)
    cursor: '#f83e19'
    colors:
      - '#3a3d43'
      - '#be3f48'
      - '#879a3b'
      - '#c5a635'
      - '#4f76a1'
      - '#855c8d'
      - '#578fa4'
      - '#b9bcba'
      - '#888987'
      - '#fb001f'
      - '#0f722f'
      - '#c47033'
      - '#186de3'
      - '#fb0067'
      - '#2e706d'
      - '#fdffb9'
  customColorSchemes:
    - name: Tabby Default
      foreground: '#cacaca'
      background: '#171717'
      cursor: '#bbbbbb'
      colors:
        - '#000000'
        - '#ff615a'
        - '#b1e969'
        - '#ebd99c'
        - '#5da9f6'
        - '#e86aff'
        - '#82fff7'
        - '#dedacf'
        - '#313131'
        - '#f58c80'
        - '#ddf88f'
        - '#eee5b2'
        - '#a5c7ff'
        - '#ddaaff'
        - '#b7fff9'
        - '#ffffff'
    - name: DimmedMonokai
      foreground: '#b9bcba'
      background: rgb(34, 37, 40)
      cursor: '#f83e19'
      colors:
        - '#3a3d43'
        - '#be3f48'
        - '#879a3b'
        - '#c5a635'
        - '#4f76a1'
        - '#855c8d'
        - '#578fa4'
        - '#b9bcba'
        - '#888987'
        - '#fb001f'
        - '#0f722f'
        - '#c47033'
        - '#186de3'
        - '#fb0067'
        - '#2e706d'
        - '#fdffb9'
  font: Consolas
  fontSize: 18
  scrollbackLines: 250000
  drawBoldTextInBrightColors: false
  rightClick: clipboard
  copyOnSelect: true
  showTabProfileIcon: true
ssh:
  warnOnClose: true
  knownHosts:
    - host: android156
      port: 22
      type: ecdsa-sha2-nistp256
      digest: yb35X5c5h78q+T1N1Kv5DQVkQuSNZ5Aop0rQdFNkJ38=
    - host: mywin10
      port: 22
      type: ecdsa-sha2-nistp256
      digest: Vb4T+3inuwI5E5/QHGacdjtflFWyWo/hqIQClpAxvgM=
    - host: 120.77.32.149
      port: 22
      type: ecdsa-sha2-nistp256
      digest: WaXUd20YfpPxBSXz9GqILI1ZWgzg44f8Ymvrm/3XwLk=
    - host: fedora42
      port: 22
      type: ecdsa-sha2-nistp256
      digest: a7mVvKIt229Ii66xycxTSzoht9li45dDZVMbZ4lTvv8=
    - host: freebsd14
      port: 22
      type: ecdsa-sha2-nistp256
      digest: wa9uhVbpfk2KAWc7pCL2/ao+Q/XG6Hzcb1cpr+vruVA=
clickableLinks: {}
accessibility: {}
appearance:
  colorSchemeMode: auto
hacks: {}
providerBlacklist: []
commandBlacklist: []
enableWelcomeTab: false
pluginBlacklist: []
profileDefaults:
  ssh:
    disableDynamicTitle: true
profileBlacklist: []
